# Generated by Django 5.0.3 on 2026-01-06 11:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bv_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RockCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('last', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('activation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
                ('total_bv', models.IntegerField(default=0)),
                ('rank', models.CharField(blank=True, default='', max_length=100)),
                ('total_left_bv', models.IntegerField(default=0)),
                ('total_right_bv', models.IntegerField(default=0)),
                ('aadhar', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('taluk', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('side', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=5, null=True)),
                ('package', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], default='Bronze', max_length=10)),
                ('current_rank', models.CharField(blank=True, max_length=50, null=True)),
                ('rank_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('bv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rank_reward', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('main_wallet', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('repurchase_wallet', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('flash_wallet', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('binary_pairs', models.IntegerField(default=0)),
                ('binary_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('parent_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sponsor_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('flash_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('stock_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('binary_eligible', models.BooleanField(default=False)),
                ('binary_eligible_date', models.DateTimeField(blank=True, null=True)),
                ('left_cf', models.IntegerField(default=0)),
                ('right_cf', models.IntegerField(default=0)),
                ('left_join_count', models.IntegerField(default=0)),
                ('right_join_count', models.IntegerField(default=0)),
                ('left_new_today', models.IntegerField(default=0)),
                ('right_new_today', models.IntegerField(default=0)),
                ('level', models.CharField(blank=True, choices=[('district', 'District Stock Point'), ('taluk', 'Taluk Gallery'), ('pincode', 'Pincode Home Shoppe')], max_length=20, null=True)),
                ('left_child', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_of', to='herbalapp.member')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='herbalapp.member')),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_downline', to='herbalapp.member')),
                ('right_child', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_of', to='herbalapp.member')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_members', to='herbalapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbalapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('joining_package', models.DecimalField(decimal_places=2, default=Decimal('3000.00'), max_digits=12)),
                ('binary_pairs', models.IntegerField(default=0)),
                ('binary_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sponsor_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('flash_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('salary_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbalapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbalapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='BonusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbalapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbalapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('district', 'District Stock Point (7%)'), ('taluk', 'Taluk Gallery (5%)'), ('pincode', 'Pincode Home Shoppe (3%)')], max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbalapp.member')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbalapp.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbalapp.member')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbalapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='RankReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_title', models.CharField(max_length=50)),
                ('left_bv_snapshot', models.BigIntegerField()),
                ('right_bv_snapshot', models.BigIntegerField()),
                ('monthly_income', models.BigIntegerField()),
                ('duration_months', models.IntegerField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('months_paid', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_rewards', to='herbalapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='RankPayoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('paid_on', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_payout_logs', to='herbalapp.member')),
                ('rank_reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_logs', to='herbalapp.rankreward')),
            ],
        ),
        migrations.CreateModel(
            name='DailyIncomeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('left_joins', models.IntegerField(default=0)),
                ('right_joins', models.IntegerField(default=0)),
                ('left_cf_before', models.IntegerField(default=0)),
                ('right_cf_before', models.IntegerField(default=0)),
                ('left_cf_after', models.IntegerField(default=0)),
                ('right_cf_after', models.IntegerField(default=0)),
                ('binary_pairs_paid', models.IntegerField(default=0)),
                ('binary_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('flashout_units', models.IntegerField(default=0)),
                ('flashout_wallet_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('washed_pairs', models.IntegerField(default=0)),
                ('total_left_bv', models.BigIntegerField(default=0)),
                ('total_right_bv', models.BigIntegerField(default=0)),
                ('salary_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rank_title', models.CharField(blank=True, max_length=100, null=True)),
                ('sponsor_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbalapp.member')),
            ],
            options={
                'unique_together': {('member', 'date')},
            },
        ),
    ]
