# Generated by Django 5.0.3 on 2025-11-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalapp', '0007_remove_member_mobile_number_remove_member_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RockCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('last', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='auto_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
