# Generated by Django 5.0.3 on 2025-11-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalapp', '0008_rockcounter_member_auto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='auto_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
