# Generated by Django 5.0.3 on 2025-11-26 09:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalapp', '0009_alter_member_auto_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_title', models.CharField(max_length=50)),
                ('left_bv_snapshot', models.BigIntegerField()),
                ('right_bv_snapshot', models.BigIntegerField()),
                ('monthly_income', models.BigIntegerField()),
                ('duration_months', models.IntegerField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('months_paid', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_rewards', to='herbalapp.member')),
            ],
        ),
        migrations.CreateModel(
            name='RankPayoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('paid_on', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_payout_logs', to='herbalapp.member')),
                ('rank_reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_logs', to='herbalapp.rankreward')),
            ],
        ),
    ]
