# Generated by Django 5.0.3 on 2025-11-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalapp', '0010_rankreward_rankpayoutlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='current_rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='rank_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
