# Generated by Django 5.0.3 on 2025-11-26 14:52

from django.db import migrations

def populate_auto_ids(apps, schema_editor):
    Member = apps.get_model("herbalapp", "Member")
    for index, member in enumerate(Member.objects.order_by("id"), start=1):
        member.auto_id = f"rocky{index:04d}"
        member.save(update_fields=["auto_id"])

def clear_auto_ids(apps, schema_editor):
    Member = apps.get_model("herbalapp", "Member")
    for member in Member.objects.all():
        member.auto_id = None
        member.save(update_fields=["auto_id"])

class Migration(migrations.Migration):

    dependencies = [
        ('herbalapp', '0011_member_current_rank_member_rank_assigned_at'),
    ]

    operations = [
        migrations.RunPython(populate_auto_ids, reverse_code=clear_auto_ids),
    ]

