# Generated by Django 5.0.3 on 2025-11-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalapp', '0012_populate_auto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='binary_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='binary_pairs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='flash_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='parent_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='repurchase_wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='sponsor_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
