# Generated by Django 5.0.3 on 2025-11-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalapp', '0013_member_binary_income_member_binary_pairs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='rank_reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
