# Generated by Django 5.0.3 on 2025-11-27 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalapp', '0014_member_bv_member_rank_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
