# Generated by Django 5.0.3 on 2025-11-27 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalapp', '0015_alter_member_joined_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIncomeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('binary_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('flash_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sponsor_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbalapp.member')),
            ],
        ),
    ]
