# Generated by Django 5.0.3 on 2025-11-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalapp', '0017_member_aadhar_member_place_alter_member_auto_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='auto_id',
        ),
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.CharField(default='rocky001', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(default='rocky001', max_length=15),
            preserve_default=False,
        ),
    ]
