# Generated by Django 5.0.3 on 2025-12-01 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalapp', '0018_remove_member_auto_id_member_member_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='auto_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='herbalapp.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='side',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=5, null=True),
        ),
    ]
