# Generated by Django 5.0.3 on 2025-12-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalapp', '0019_member_auto_id_alter_member_parent_alter_member_side'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='rank_reward',
        ),
        migrations.AddField(
            model_name='member',
            name='flash_wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='bv_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
