# Generated by Django 5.0.3 on 2025-12-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalapp', '0021_income_total_income_member_binary_eligible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='total_income',
        ),
        migrations.AlterField(
            model_name='bonusrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='commission',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='commissionrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='incomerecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
