# Generated by Django 5.0.3 on 2025-12-03 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalapp', '0022_remove_income_total_income_alter_bonusrecord_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_downline', to='herbalapp.member'),
        ),
    ]
