# Generated by Django 5.0.3 on 2025-12-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalapp', '0023_member_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=10, null=True),
        ),
    ]
