# Generated by Django 5.0.3 on 2025-12-05 12:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalapp', '0025_member_activation_amount_member_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='main_wallet',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
