# Generated by Django 5.0.3 on 2025-12-07 10:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbalapp', '0027_alter_member_main_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='stock_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
